"""after database upload

Revision ID: 79d88d3ef3e2
Revises: 33baca56788d
Create Date: 2020-12-15 16:38:57.685030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d88d3ef3e2'
down_revision = '33baca56788d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
