"""models updated

Revision ID: 33baca56788d
Revises: 640e96d36deb
Create Date: 2020-12-15 15:21:37.478908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33baca56788d'
down_revision = '640e96d36deb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
    sa.Column('ArtistId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ArtistId', name=op.f('pk_Artist'))
    )
    op.create_table('Employee',
    sa.Column('EmployeeId', sa.Integer(), nullable=False),
    sa.Column('LastName', sa.Text(), nullable=False),
    sa.Column('FirstName', sa.Text(), nullable=False),
    sa.Column('Title', sa.Text(), nullable=True),
    sa.Column('BirthDate', sa.DateTime(), nullable=True),
    sa.Column('HireDate', sa.DateTime(), nullable=True),
    sa.Column('Address', sa.Text(), nullable=True),
    sa.Column('City', sa.Text(), nullable=True),
    sa.Column('State', sa.Text(), nullable=True),
    sa.Column('Country', sa.Text(), nullable=True),
    sa.Column('PostalCode', sa.Text(), nullable=True),
    sa.Column('Phone', sa.Text(), nullable=True),
    sa.Column('Fax', sa.Text(), nullable=True),
    sa.Column('Email', sa.Text(), nullable=True),
    sa.Column('ReportsTo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ReportsTo'], ['Employee.EmployeeId'], name=op.f('fk_Employee_ReportsTo_Employee')),
    sa.PrimaryKeyConstraint('EmployeeId', name=op.f('pk_Employee'))
    )
    op.create_index('IFK_EmployeeReportsTo', 'Employee', ['ReportsTo'], unique=False)
    op.create_table('Genre',
    sa.Column('GenreId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('GenreId', name=op.f('pk_Genre'))
    )
    op.create_table('MediaType',
    sa.Column('MediaTypeId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('MediaTypeId', name=op.f('pk_MediaType'))
    )
    op.create_table('Playlist',
    sa.Column('PlaylistId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('PlaylistId', name=op.f('pk_Playlist'))
    )
    op.create_table('Album',
    sa.Column('AlbumId', sa.Integer(), nullable=False),
    sa.Column('Title', sa.Text(), nullable=False),
    sa.Column('ArtistId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ArtistId'], ['Artist.ArtistId'], name=op.f('fk_Album_ArtistId_Artist')),
    sa.PrimaryKeyConstraint('AlbumId', name=op.f('pk_Album'))
    )
    op.create_index('IFK_AlbumArtistId', 'Album', ['ArtistId'], unique=False)
    op.create_table('Customer',
    sa.Column('CustomerId', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.Text(), nullable=False),
    sa.Column('LastName', sa.Text(), nullable=False),
    sa.Column('Company', sa.Text(), nullable=True),
    sa.Column('Address', sa.Text(), nullable=True),
    sa.Column('City', sa.Text(), nullable=True),
    sa.Column('State', sa.Text(), nullable=True),
    sa.Column('Country', sa.Text(), nullable=True),
    sa.Column('PostalCode', sa.Text(), nullable=True),
    sa.Column('Phone', sa.Text(), nullable=True),
    sa.Column('Fax', sa.Text(), nullable=True),
    sa.Column('Email', sa.Text(), nullable=False),
    sa.Column('SupportRepId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SupportRepId'], ['Employee.EmployeeId'], name=op.f('fk_Customer_SupportRepId_Employee')),
    sa.PrimaryKeyConstraint('CustomerId', name=op.f('pk_Customer'))
    )
    op.create_index('IFK_CustomerSupportRepId', 'Customer', ['SupportRepId'], unique=False)
    op.create_table('Invoice',
    sa.Column('InvoiceId', sa.Integer(), nullable=False),
    sa.Column('InvoiceDate', sa.DateTime(), nullable=False),
    sa.Column('BillingAddress', sa.Text(), nullable=True),
    sa.Column('BillingCity', sa.Text(), nullable=True),
    sa.Column('BillingState', sa.Text(), nullable=True),
    sa.Column('BillingCountry', sa.Text(), nullable=True),
    sa.Column('BillingPostalCode', sa.Text(), nullable=True),
    sa.Column('Total', sa.Numeric(), nullable=False),
    sa.Column('CustomerId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerId'], ['Customer.CustomerId'], name=op.f('fk_Invoice_CustomerId_Customer')),
    sa.PrimaryKeyConstraint('InvoiceId', name=op.f('pk_Invoice'))
    )
    op.create_index('IFK_InvoiceCustomerId', 'Invoice', ['CustomerId'], unique=False)
    op.create_table('Track',
    sa.Column('TrackId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=False),
    sa.Column('Composer', sa.Text(), nullable=True),
    sa.Column('Milliseconds', sa.Integer(), nullable=False),
    sa.Column('Bytes', sa.Integer(), nullable=True),
    sa.Column('UnitPrice', sa.Numeric(), nullable=False),
    sa.Column('AlbumId', sa.Integer(), nullable=True),
    sa.Column('GenreId', sa.Integer(), nullable=True),
    sa.Column('MediaTypeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AlbumId'], ['Album.AlbumId'], name=op.f('fk_Track_AlbumId_Album')),
    sa.ForeignKeyConstraint(['GenreId'], ['Genre.GenreId'], name=op.f('fk_Track_GenreId_Genre')),
    sa.ForeignKeyConstraint(['MediaTypeId'], ['MediaType.MediaTypeId'], name=op.f('fk_Track_MediaTypeId_MediaType')),
    sa.PrimaryKeyConstraint('TrackId', name=op.f('pk_Track'))
    )
    op.create_index('IFK_TrackAlbumId', 'Track', ['AlbumId'], unique=False)
    op.create_index('IFK_TrackGenreId', 'Track', ['GenreId'], unique=False)
    op.create_index('IFK_TrackMediaTypeId', 'Track', ['MediaTypeId'], unique=False)
    op.create_table('InvoiceLine',
    sa.Column('InvoiceLineId', sa.Integer(), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('InvoiceId', sa.Integer(), nullable=False),
    sa.Column('TrackId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['InvoiceId'], ['Invoice.InvoiceId'], name=op.f('fk_InvoiceLine_InvoiceId_Invoice')),
    sa.ForeignKeyConstraint(['TrackId'], ['Track.TrackId'], name=op.f('fk_InvoiceLine_TrackId_Track')),
    sa.PrimaryKeyConstraint('InvoiceLineId', name=op.f('pk_InvoiceLine'))
    )
    op.create_index('IFK_InvoiceLineInvoiceId', 'InvoiceLine', ['InvoiceId'], unique=False)
    op.create_index('IFK_InvoiceLineTrackId', 'InvoiceLine', ['TrackId'], unique=False)
    op.create_table('PlaylistTrack',
    sa.Column('PlaylistId', sa.Integer(), nullable=False),
    sa.Column('TrackId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PlaylistId'], ['Playlist.PlaylistId'], name=op.f('fk_PlaylistTrack_PlaylistId_Playlist')),
    sa.ForeignKeyConstraint(['TrackId'], ['Track.TrackId'], name=op.f('fk_PlaylistTrack_TrackId_Track')),
    sa.PrimaryKeyConstraint('PlaylistId', 'TrackId', name=op.f('pk_PlaylistTrack'))
    )
    op.create_index('IFK_PlaylistTrackTrackId', 'PlaylistTrack', ['TrackId'], unique=False)
    op.drop_index('my_index', table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_models')
    )
    op.create_index('my_index', 'models', ['name'], unique=1)
    op.drop_index('IFK_PlaylistTrackTrackId', table_name='PlaylistTrack')
    op.drop_table('PlaylistTrack')
    op.drop_index('IFK_InvoiceLineTrackId', table_name='InvoiceLine')
    op.drop_index('IFK_InvoiceLineInvoiceId', table_name='InvoiceLine')
    op.drop_table('InvoiceLine')
    op.drop_index('IFK_TrackMediaTypeId', table_name='Track')
    op.drop_index('IFK_TrackGenreId', table_name='Track')
    op.drop_index('IFK_TrackAlbumId', table_name='Track')
    op.drop_table('Track')
    op.drop_index('IFK_InvoiceCustomerId', table_name='Invoice')
    op.drop_table('Invoice')
    op.drop_index('IFK_CustomerSupportRepId', table_name='Customer')
    op.drop_table('Customer')
    op.drop_index('IFK_AlbumArtistId', table_name='Album')
    op.drop_table('Album')
    op.drop_table('Playlist')
    op.drop_table('MediaType')
    op.drop_table('Genre')
    op.drop_index('IFK_EmployeeReportsTo', table_name='Employee')
    op.drop_table('Employee')
    op.drop_table('Artist')
    # ### end Alembic commands ###
